logging:
  level:
    root: error
    cloud:
      sonam: debug
info:
  app:
    name: Springboot Application
    description: This is a Springboot application
    version: 1.0.0

management:
  endpoint:
    health:
      show-details: always
#spring:
#  webflux:
#    static-path-pattern: file:/Users/ssamdupk/Documents/bitbucket/reactive-rest-service/videofiles
#  resources.static-locations: file:/Users/ssamdupk/Documents/bitbucket/reactive-rest-service/videofiles

server:
#  port: 8080
  port: 9001
trustOrigin: http://localhost:8080


spring:
  codec:
    max-in-memory-size: 100MB

aws:
  s3:
    region:
    accessKeyId:
    secretAccessKey:
    bucket:
    endpoint: https://sfo2.digitaloceanspaces.com
    subdomain:
    videoPath: videoapp/1/

#spaceBucketRegion: sfo2
videoPath: videoapp/1/
bucket: sonam

spaceAccessKey:
spaceSecretKey:
imageAclHeader: x-amz-acl
imageAclValue: public-read